CREATE TABLE Category(
	category_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(25) UNIQUE NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Books(
	book_id INTEGER AUTO_INCREMENT PRIMARY KEY,
	category_id INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    isbn VARCHAR(25) UNIQUE,
    page_number SMALLINT,
    unit_price DECIMAL(6,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    book_cover MEDIUMBLOB NOT NULL, 
	FOREIGN KEY (category_id) REFERENCES Category(category_id)
);

CREATE TABLE Sales(
	sale_id INTEGER AUTO_INCREMENT PRIMARY KEY,
    sale_date DATETIME NOT NULL,
    staff_name VARCHAR(100) NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SaleDetail(
	book_id INTEGER NOT NULL,
    sale_id INTEGER NOT NULL,
    qty INTEGER NOT NULL,
    unit_price DECIMAL(6,2) NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (sale_id, book_id),
    FOREIGN KEY (sale_id) REFERENCES Sales(sale_id),
    FOREIGN KEY (book_id) REFERENCES Books(book_id)
);

UPDATE books SET book_cover = LOAD_FILE('C:/xampp/htdocs/book_shop_ass1_php/book_cover/cb-1.jpg') WHERE book_id = 1;